theme: jekyll-theme-minimal
title: Sujata Roy
#logo: "assets/img/GitHub_portfolio_pic.jpg?raw=true" # your photo (or logo) here
<p>"assets/img/GitHub_portfolio_pic.jpg?raw=true"</p>
<img class="one" src="ocean.jpg" width="300" height="300"><br>
description: >
  <div style="text-align: center;">
      <a style="text-decoration:none" href="https://www.linkedin.com/in/sujata-roy/">
          <img src="https://cdn-icons-png.flaticon.com/128/3536/3536569.png" alt="LinkedIn" style="width: 30px; height: 30px; margin-right: 10px;">
      </a>
      <a style="text-decoration:none" href="https://github.com/sujata-roy">
  </div>
  <div style="text-align: center;">
      <p>Software Engineer</p>
  </div>